#!/bin/bash
# Free and open-source media player software
# Release: 2009    Genre: Multimedia

printf "\e[32mDownloading Kodi ..." > /dev/tty1
wget -q 'https://github.com/krishenriksen/xbmc-rg351p/releases/download/1.0.0/kodi.zip'

printf "\e[32mExtracting ..." > /dev/tty1
unzip -qq -o kodi.zip -d ../

printf "\e[32mCleaning up ..." > /dev/tty1
rm -rf kodi.zip