#!/bin/bash
# Cloud Saves for Anbernic devices.
# Release: 2021    Genre: System

printf "\e[32mDownloading AnberCloud ..." > /dev/tty1
wget -q -O "../AnberCloud Setup.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/AnberCloud%20Setup.sh'
wget -q -O "../AnberCloud Sync.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/AnberCloud%20Sync.sh'

chmod +x "../AnberCloud Setup.sh" "../AnberCloud Sync.sh"