#!/bin/bash
# Change AnberPorts between SDL and Dialog
# Release: 2021    Genre: System

if [[ `cat ./type.txt` == "sdl" ]]; then
  echo dialog > ./type.txt
else
  echo sdl > ./type.txt
fi

if id "ark" &>/dev/null || id "odroid" &>/dev/null; then
  pgrep -f oga_controls | sudo xargs kill -9
else
  pgrep -f oga_controls | xargs kill -9
fi

pgrep -f AnberPorts | xargs kill -9
pgrep -f AnberPortsSDL | xargs kill -9