#!/bin/bash
# Exit to emulationstation
# Release: 2021    Genre: System

if id "ark" &>/dev/null || id "odroid" &>/dev/null; then
  pgrep -f oga_controls | sudo xargs kill -9
else
  pgrep -f oga_controls | xargs kill -9
fi

pgrep -f AnberPorts | xargs kill -9
pgrep -f AnberPortsSDL | xargs kill -9

if systemctl --all --type service | grep -q 'emustation'; then
  systemctl restart emustation
else
  sudo systemctl restart emulationstation
fi