#!/bin/bash
# Copyright (c) 2021
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the
# Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA
#
# Authored by: Kris Henriksen <krishenriksen.work@gmail.com>
#
# AnberPorts
#
BINDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/bin"

Menu() {
  selection=(dialog \
  --backtitle "AnberPorts $1" \
  --title "[ Main Menu ]" \
  --no-collapse \
  --clear \
  --cancel-label "Select + Start to Exit" \
  --menu "$2" 15 55 15)

  local options=()

  for file in ./scripts/${1,,}/*; do
    if [[ -f $file ]]; then
      DESCRIPTION=`cat $file | sed -n '2p'`
      options+=($(basename "$file") "$DESCRIPTION")
    fi
  done

  choice=$("${selection[@]}" "${options[@]}" 2>&1 > /dev/tty1)
  execute="./scripts/${1,,}/$choice"

  if [[ -f $execute ]]; then
    bash $execute
  fi
}

ExitMenu() {
  if id "ark" &>/dev/null || id "odroid" &>/dev/null; then
    pgrep -f oga_controls | sudo xargs kill -9
    sudo systemctl restart emulationstation
  else
    pgrep -f oga_controls | xargs kill -9
    systemctl restart emustation
  fi
}

#
# Joystick controls
#
if id "ark" &>/dev/null || id "odroid" &>/dev/null; then
  sudo $BINDIR/oga_controls AnberPorts &
else
  $BINDIR/oga_controls AnberPorts &
fi

MainMenu() {
  local options=(
    Games "Open Source Ports of Game Engines"
    Multimedia "Multiple Media Formats Apps"
    Streaming "Game Streaming Services"
    Beta "Early Access & Beta Apps"
    System "Improvement To System Functions"
  )

  while true; do
    selection=(dialog \
   	--backtitle "AnberPorts $1" \
   	--title "[ Main Menu ]" \
   	--no-collapse \
   	--clear \
	--cancel-label "Select + Start to Exit" \
    --menu "$2" 15 55 15)

    choices=$("${selection[@]}" "${options[@]}" 2>&1 > /dev/tty1)

    for choice in $choices; do
      case $choice in
        *) Menu $choice ;;
      esac
    done
  done
}

MainMenu "$1" "$2"