#!/bin/bash
# Amazon Luna is a cloud gaming platform developed and operated by Amazon
# Release: 2020    Genre: Cloud gaming service

printf "\e[32mDownloading Amazon Luna ..." > /dev/tty1
wget -q 'https://github.com/krishenriksen/weston-rg351p/releases/download/1.0.0/Amazon.Luna.sh'
wget -q 'https://github.com/krishenriksen/weston-rg351p/releases/download/1.0.0/weston.zip'
wget -q 'https://github.com/krishenriksen/weston-rg351p/releases/download/1.0.0/chromium.zip'

printf "\e[32mExtracting ..." > /dev/tty1
unzip -qq -o weston.zip -d ../
unzip -qq -o chromium.zip -d ../

mv Amazon.Luna.sh ../Amazon\ Luna.sh

printf "\e[32mCleaning up ..." > /dev/tty1
rm -rf weston.zip
rm -rf chromium.zip