#!/bin/bash
# Google Stadia is a cloud gaming service developed and operated by Google
# Release: 2019    Genre: Cloud gaming service

printf "\e[32mDownloading Google Stadia ..." > /dev/tty1
wget -q 'https://github.com/krishenriksen/weston-rg351p/releases/download/1.0.0/Google.Stadia.sh'
wget -q 'https://github.com/krishenriksen/weston-rg351p/releases/download/1.0.0/weston.zip'
wget -q 'https://github.com/krishenriksen/weston-rg351p/releases/download/1.0.0/chromium.zip'

printf "\e[32mExtracting ..." > /dev/tty1
unzip -qq -o weston.zip -d ../
unzip -qq -o chromium.zip -d ../

mv Google.Stadia.sh ../Google\ Stadia.sh

printf "\e[32mCleaning up ..." > /dev/tty1
rm -rf weston.zip
rm -rf chromium.zip