#!/bin/bash
# Video game developed by Monolith Productions.
# Release: 1997    Genre: First-person shooter

printf "\e[32mDownloading Blood ...\n" > /dev/tty1

wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/blood.zip'
if [[ $? -ne 0 ]]; then
  printf "\e[32mDownloading failed, trying another server ...\n" > /dev/tty1

  wget 'http://139.196.213.206/releases/anberports/misc/blood.zip'
  wget -q -O "../Blood.sh" 'http://139.196.213.206/releases/anberports/misc/Blood.sh'
else
  wget -q -O "../Blood.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Blood.sh'
fi

printf "\e[32mPlease copy games files to your Blood directory! ...\n" > /dev/tty1
unzip -qq -o blood.zip -d ../
chmod +x "../Blood.sh"

mkdir -p ~/.config/nblood
mv ../Blood/nblood.cfg ~/.config/nblood/
mv ../Blood/settings.cfg ~/.config/nblood/

printf "\e[32mCleaning Up ...\n" > /dev/tty1
rm -rf blood.zip