#!/bin/bash
# Shooter game developed by Parallax Software.
# Release: 1995    Genre: First-person shooter

printf "\e[32mDownloading Descent ...\n" > /dev/tty1

wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/descent.zip'
if [[ $? -ne 0 ]]; then
  printf "\e[32mDownloading failed, trying another server ...\n" > /dev/tty1

  wget 'http://139.196.213.206/releases/anberports/misc/descent.zip'
  wget -q -O "../Descent.sh" 'http://139.196.213.206/releases/anberports/misc/Descent.sh'
else
  wget -q -O "../Descent.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Descent.sh'
fi

printf "\e[32mExtracting ...\n" > /dev/tty1
unzip -qq -o descent.zip -d ../
chmod +x "../Descent.sh"

printf "\e[32mCleaning Up ...\n" > /dev/tty1
rm -rf descent.zip