#!/bin/bash
# Doom II, also known as Doom II: Hell on Earth.
# Release: 1994    Genre: First-person shooter

printf "\e[32mDownloading Doom 2 ..." > /dev/tty1
wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/doom2.zip'
wget -q -O "../Doom 2.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Doom%202.sh'

printf "\e[32mPlease copy 'Doom2.wad' to your doom2 directory! ..." > /dev/tty1
unzip -qq -o doom2.zip -d ../
chmod +x "../Doom 2.sh"

printf "\e[32mCleaning Up ..." > /dev/tty1
rm -rf doom2.zip