#!/bin/bash
# Features the adventures of the titular Duke Nukem.
# Release: 1996    Genre: First-person shooter

printf "\e[32mDownloading Eduke32 ..." > /dev/tty1
wget -q 'https://media.githubusercontent.com/media/krishenriksen/AnberPorts/master/misc/eduke32.zip'
wget -q -O "Duke Nukem 3D.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Duke%20Nukem%203D.sh'

printf "\e[32mPlease copy 'DUKE3D.GRP' to your eduke32 directory! ..." > /dev/tty1
unzip -qq -o eduke32.zip -d ../
chmod +x "Duke Nukem 3D.sh"
mv -f "Duke Nukem 3D.sh" ../

mkdir -p ~/.config/eduke32
cp -rf ../eduke32/eduke32.cfg ~/.config/eduke32/

printf "\e[32mCleaning Up ..." > /dev/tty1
rm -rf eduke32.zip