#!/bin/bash
# PowerSlave, known as Exhumed in Europe.
# Release: 1996    Genre: First-person shooter

printf "\e[32mDownloading Exhumed / PowerSlave ..." > /dev/tty1
wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/exhumed.zip'
wget -q -O "Exhumed.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Exhumed.sh'

printf "\e[32mPlease copy games files to your Exhumed directory! ..." > /dev/tty1
unzip -qq -o exhumed.zip -d ../
chmod +x "Exhumed.sh"
mv -f "Exhumed.sh" ../

mkdir -p ~/.config/rednukem
mv ../Exhumed/rednukem.cfg ~/.config/rednukem/
mv ../Exhumed/settings.cfg ~/.config/rednukem/

printf "\e[32mCleaning Up ..." > /dev/tty1
rm -rf exhumed.zip