#!/bin/bash
# Flashback, released as Flashback: The Quest for Identity.
# Release: 1992    Genre: First-person shooter

printf "\e[32mDownloading Flashback ..." > /dev/tty1

wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/flashback.zip'
if [[ $? -ne 0 ]]; then
  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1

  wget 'http://139.196.213.206/releases/anberports/misc/flashback.zip'
  wget -q -O "../Flashback.sh" 'http://139.196.213.206/releases/anberports/misc/Flashback.sh'
else
  wget -q -O "../Flashback.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Flashback.sh'
fi

printf "\e[32mExtracting ..." > /dev/tty1
unzip -qq -o flashback.zip -d ../
chmod +x "../Flashback.sh"

printf "\e[32mCleaning Up ..." > /dev/tty1
rm -rf flashback.zip