#!/bin/bash
# The game combine shooting combat, puzzles, and storytelling.
# Release: 2001    Genre: First-person shooter

printf "\e[32mDownloading Half-Life: Blue Shift ..." > /dev/tty1
wget -q 'https://media.githubusercontent.com/media/krishenriksen/AnberPorts/master/misc/half-life.zip'
wget -q -O "Half-Life Blue Shift.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Half-Life%20Blue%20Shift.sh'

printf "\e[32mExtracting ..." > /dev/tty1
unzip -qq -o half-life.zip -d ../
chmod +x "Half-Life Blue Shift.sh"
mv -f "Half-Life Blue Shift.sh" ../

printf "\e[32mCleaning Up ..." > /dev/tty1
rm -rf half-life.zip