#!/bin/bash
# Commander Keen is a series of side-scrolling platform.
# Release: 1990    Genre: Side-scrolling platform

printf "\e[32mDownloading Commander Keen ...\n" > /dev/tty1

wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/keen.zip'
if [[ $? -ne 0 ]]; then
  printf "\e[32mDownloading failed, trying another server ...\n" > /dev/tty1

  wget 'http://139.196.213.206/releases/anberports/misc/keen.zip'
  wget -q -O "../Commander Genius.sh" 'http://139.196.213.206/releases/anberports/misc/Commander%20Genius.sh'
else
  wget -q -O "../Commander Genius.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Commander%20Genius.sh'
fi

printf "\e[32mPlease copy 'keen' folders to your cgenius/games directory! ...\n" > /dev/tty1
unzip -qq -o keen.zip -d ../
chmod +x "../Commander Genius.sh"

printf "\e[32mCleaning Up ...\n" > /dev/tty1
rm -rf keen.zip