#!/bin/bash
# Video game franchise created by Jordan Mechner
# Release: 1999    Genre: Side-scrolling platform

printf "\e[32mDownloading Prince of Persia ...\n" > /dev/tty1

wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/sdlpop.zip'
if [[ $? -ne 0 ]]; then
  printf "\e[32mDownloading failed, trying another server ...\n" > /dev/tty1

  wget 'http://139.196.213.206/releases/anberports/misc/sdlpop.zip'
  wget -q -O "../Prince of Persia.sh" 'http://139.196.213.206/releases/anberports/misc/Prince%20of%20Persia.sh'
else
  wget -q -O "../Prince of Persia.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Prince%20of%20Persia.sh'
fi

printf "\e[32mExtracting ...\n" > /dev/tty1
unzip -qq -o sdlpop.zip -d ../
chmod +x "../Prince of Persia.sh"

printf "\e[32mCleaning Up ...\n" > /dev/tty1
rm -rf sdlpop.zip