#!/bin/bash
# It differs from previous games by excluding a story-based.
# Release: 1999    Genre: First-person shooter

printf "\e[32mDownloading Quake 3 ..." > /dev/tty1

wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/quake3.zip'
if [[ $? -ne 0 ]]; then
  printf "\e[32mDownloading failed, trying another server ..." > /dev/tty1

  wget 'http://139.196.213.206/releases/anberports/misc/quake3.zip'
  wget -q -O "../Quake 3.sh" 'http://139.196.213.206/releases/anberports/misc/Quake%203.sh'
else
  wget -q -O "../Quake 3.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Quake%203.sh'
fi

printf "\e[32mPlease copy '*.pk3' to your quake3/baseq3 directory! ..." > /dev/tty1
unzip -qq -o quake3.zip -d ../
chmod +x "../Quake 3.sh"

printf "\e[32mCleaning up ..." > /dev/tty1
rm -rf quake3.zip