#!/bin/bash
# In the game, players must find their way through various maze-like.
# Release: 1997    Genre: First-person shooter

printf "\e[32mDownloading Quake 2 ...\n" > /dev/tty1

wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/quake2.zip'
if [[ $? -ne 0 ]]; then
  printf "\e[32mDownloading failed, trying another server ...\n" > /dev/tty1

  wget 'http://139.196.213.206/releases/anberports/misc/quake2.zip'
  wget -q -O "../Quake 2.sh" 'http://139.196.213.206/releases/anberports/misc/Quake%202.sh'
else
  wget -q -O "../Quake 2.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Quake%202.sh'
fi

printf "\e[32mPlease copy '*.pak' to your quake2/baseq2 directory! ...\n" > /dev/tty1
unzip -qq -o quake2.zip -d ../
chmod +x "../Quake 2.sh"

if [ ! -d "~/.yq2" ]; then
  mkdir ~/.yq2
fi

printf "\e[32mCleaning Up ...\n" > /dev/tty1
rm -rf quake2.zip