#!/bin/bash
# In the game, players must find their way through various maze-like.
# Release: 1996    Genre: First-person shooter

printf "\e[32mDownloading Quake 1 ...\n" > /dev/tty1

wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/quake1.zip'
if [[ $? -ne 0 ]]; then
  printf "\e[32mDownloading failed, trying another server ...\n" > /dev/tty1

  wget 'http://139.196.213.206/releases/anberports/misc/quake1.zip'
  wget -q -O "../Quake 1.sh" 'http://139.196.213.206/releases/anberports/misc/Quake%201.sh'
else
  wget -q -O "../Quake 1.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Quake%201.sh'
fi

printf "\e[32mPlease copy 'PAK0.PAK' to your quake1 directory! ...\n" > /dev/tty1
unzip -qq -o quake1.zip -d ../
chmod +x "../Quake 1.sh"

printf "\e[32mCleaning Up ...\n" > /dev/tty1
rm -rf quake1.zip