#!/bin/bash
# The game is a first person shooter with a variety of weapons.
# Release: 1997    Genre: First-person shooter game

printf "\e[32mDownloading Redneck Rampage ..." > /dev/tty1
wget -q 'https://media.githubusercontent.com/media/krishenriksen/AnberPorts/master/misc/redneck-rampage.zip'
wget -q -O "Redneck Rampage.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Redneck%20Rampage.sh'

printf "\e[32mPlease copy game files to your Redneck Rampage directory! ..." > /dev/tty1
unzip -qq -o redneck-rampage.zip -d ../
chmod +x "Redneck Rampage.sh"
mv -f "Redneck Rampage.sh" ../

mkdir -p ~/.config/rednukem
mv "../Redneck Rampage/rednukem.cfg" ~/.config/rednukem/
mv "../Redneck Rampage/settings.cfg" ~/.config/rednukem/

printf "\e[32mCleaning Up ..." > /dev/tty1
rm -rf redneck-rampage.zip