#!/bin/bash
# Video game developed by Xatrix Entertainment.
# Release: 1998    Genre: First-person shooter

printf "\e[32mDownloading Redneck Rampage Rides Again ..." > /dev/tty1
wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/redneck-rampage-rides-again.zip'
wget -q -O "../Redneck Rampage Rides Again.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Redneck%20Rampage%20Rides%20Again.sh'

printf "\e[32mPlease copy game files to your Redneck Rampage Rides Again directory! ..." > /dev/tty1
unzip -qq -o redneck-rampage-rides-again.zip -d ../
chmod +x "../Redneck Rampage Rides Again.sh"

mkdir -p ~/.config/rednukem
mv "../Redneck Rampage Rides Again/rednukem.cfg" ~/.config/rednukem/
mv "../Redneck Rampage Rides Again/settings.cfg" ~/.config/rednukem/

printf "\e[32mCleaning Up ..." > /dev/tty1
rm -rf redneck-rampage-rides-again.zip