#!/bin/bash
# Classic styled kart racer, complete with beautiful courses, and wacky items.
# Release: 2018    Genre: First-person shooter

printf "\e[32mDownloading Sonic Robo Blast 2 Kart ..." > /dev/tty1
wget -q 'https://media.githubusercontent.com/media/krishenriksen/AnberPorts/master/misc/sonic-robo-blast-2-kart.zip'
wget -q 'https://media.githubusercontent.com/media/krishenriksen/AnberPorts/master/misc/sonic-robo-blast-2-kart.z01'
wget -q 'https://media.githubusercontent.com/media/krishenriksen/AnberPorts/master/misc/sonic-robo-blast-2-kart.z02'
wget -q -O "../Sonic Robo Blast 2 Kart.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Sonic%20Robo%20Blast%202%20Kart.sh'
chmod +x "../Sonic Robo Blast 2 Kart.sh"

printf "\e[32mExtracting ..." > /dev/tty1
zip -F sonic-robo-blast-2-kart.zip --out single-archive.zip
unzip -qq -o single-archive.zip -d ../

printf "\e[32mCleaning Up ..." > /dev/tty1
rm -rf sonic-robo-blast-2-kart.zip
rm -rf sonic-robo-blast-2-kart.z01
rm -rf sonic-robo-blast-2-kart.z02
rm -rf single-archive.zip