#!/bin/bash
# Classic styled kart racer, complete with beautiful courses, and wacky items.
# Release: 2018    Genre: First-person shooter

printf "\e[32mDownloading Sonic Robo Blast 2 Kart ..." > /dev/tty1
wget -q 'https://media.githubusercontent.com/media/krishenriksen/AnberPorts/master/misc/sonic-robo-blast-2-kart.tar.xz'
wget -q -O "../Sonic Robo Blast 2 Kart.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Sonic%20Robo%20Blast%202%20Kart.sh'
chmod +x "../Sonic Robo Blast 2 Kart.sh"

printf "\e[32mExtracting ..." > /dev/tty1
unzip -qq -o sonic-robo-blast-2-kart.zip -d ../

printf "\e[32mCleaning Up ..." > /dev/tty1
rm -rf sonic-robo-blast-2-kart.zip