#!/bin/bash
# The game is set aboard a space station in a cyberpunk vision.
# Release: 1994    Genre: First-person shooter

printf "\e[32mDownloading System Shock ..." > /dev/tty1
wget -q 'https://media.githubusercontent.com/media/krishenriksen/AnberPorts/master/misc/system-shock.zip'
wget -q -O "System Shock.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/System%20Shock.sh'

printf "\e[32mPlease copy game 'data' folder to your system-shock/res directory! ..." > /dev/tty1
unzip -qq -o system-shock.zip -d ../
chmod +x "System Shock.sh"
mv -f "System Shock.sh" ../

printf "\e[32mCleaning Up ..." > /dev/tty1
rm -rf system-shock.zip