#!/bin/bash
# The player controls a child who has fallen into the Underground.
# Release: 2015    Genre: First-person shooter

printf "\e[32mDownloading Undertale ...\n" > /dev/tty1

wget -q 'https://github.com/krishenriksen/AnberPorts/raw/master/misc/undertale.zip'
if [[ $? -ne 0 ]]; then
  printf "\e[32mDownloading failed, trying another server ...\n" > /dev/tty1

  wget 'http://139.196.213.206/releases/anberports/misc/undertale.zip'
  wget -q -O "../Undertale.sh" 'http://139.196.213.206/releases/anberports/misc/Undertale.sh'
else
  wget -q -O "../Undertale.sh" 'https://raw.githubusercontent.com/krishenriksen/AnberPorts/master/misc/Undertale.sh'
fi

printf "\e[32mPlease copy game files to your undertale directory! ...\n" > /dev/tty1
unzip -qq -o undertale.zip -d ../
chmod +x "../Undertale.sh"

printf "\e[32mCleaning Up ...\n" > /dev/tty1
rm -rf undertale.zip